/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sosrs;

import java.util.Arrays;
import java.util.List;
import sosrs.DoencaManager;
import sosrs.Doenca;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JList;

public class Identificador extends javax.swing.JFrame {
 public JList<String> mostrarPossiveisDeTratamentoList;
    /**
     * Creates new form Identificador
     */
    public Identificador() {
        initComponents();
        setupEvents();
    }
     private void setupEvents() {
        EnviarSintomasBTN.addActionListener(e -> identificarDoencas());
    }
     
     private void identificarDoencas() {
         String sintomasInput = TxtIdentificar.getText().trim().toLowerCase();

    if (sintomasInput.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, informe os sintomas.");
        return;
    }

    List<String> sintomas = Arrays.asList(sintomasInput.split("\\s*,\\s*"));

    DefaultListModel<String> model = new DefaultListModel<>();
    for (String sintoma : sintomas) {
        boolean sintomaEncontrado = false;
        String sintomaNormalizado = sintoma.trim();
        for (Doenca doenca : DoencaManager.getInstance().getDoencas()) {
            for (String sintomaDoenca : doenca.getSintomas()) {
                if (sintomaDoenca.equalsIgnoreCase(sintomaNormalizado)) {
                    model.addElement(doenca.toString());
                    sintomaEncontrado = true;
                    break;
                }
            }
            if (sintomaEncontrado) {
                break;
            }
        }
        if (!sintomaEncontrado) {
            model.addElement("Nenhuma doença encontrada com o sintoma: " + sintoma);
        }
    }

    if (mostrarPossiveisDeTratamentoList == null) {
        mostrarPossiveisDeTratamentoList = new javax.swing.JList<>();
        jScrollPane1.setViewportView(mostrarPossiveisDeTratamentoList);
    }

    mostrarPossiveisDeTratamentoList.setModel(model);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxtIdentificar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        EnviarSintomasBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MostrarPossiveisDeTratamento = new javax.swing.JTextArea();

        jLabel1.setText("Que tipo de sintomas voce esta tendo?");

        EnviarSintomasBTN.setText("Enviar Sintomas!");

        MostrarPossiveisDeTratamento.setColumns(20);
        MostrarPossiveisDeTratamento.setRows(5);
        jScrollPane1.setViewportView(MostrarPossiveisDeTratamento);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                            .addComponent(TxtIdentificar))
                        .addComponent(EnviarSintomasBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtIdentificar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EnviarSintomasBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Identificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Identificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Identificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Identificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Identificador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnviarSintomasBTN;
    private javax.swing.JTextArea MostrarPossiveisDeTratamento;
    private javax.swing.JTextField TxtIdentificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
