/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sosrs;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.Arrays;
import sosrs.DoencaManager;


public class CadastrarDeS extends javax.swing.JFrame {
private Menu menu;
    /**
     * Creates new form CadastrarDeS
     */
    public CadastrarDeS() {
         this.menu = menu;
        initComponents();
        setupEvents();
    }

 private void setupEvents() {
CadastroBtn.addActionListener(e -> cadastrarDoenca());
        FotoBtn.addActionListener(e -> capturarFotoAnimal());

         {
             
             

            
            }
 }
 public void actionPerformed(ActionEvent e) {
                // Quando o botão de cadastro for clicado

        // Extrai os dados dos campos
        String nome = txtNomeDoenca.getText().trim();
        String sintomas = txtSintomas.getText().trim();
        String tratamento = tratamentoTxtField.getText().trim();
        String informacoes = InfoDoenca.getText().trim();
        boolean picada = CasoforPicadacheckbox.isSelected();

        // Verifica se o nome da doença foi preenchido
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, informe o nome da doença.");
            return;
        }

        // Cria uma nova instância de Doenca
        Doenca novaDoenca = new Doenca(nome, Arrays.asList(sintomas.split(",")), tratamento, informacoes, picada);

        // Aqui você pode adicionar a lógica para salvar a doença em algum lugar,
        // como um banco de dados ou um arquivo

        // Exemplo de exibição dos dados
        JOptionPane.showMessageDialog(null, "Doença cadastrada com sucesso:\n" + novaDoenca.toString());

        // Limpa os campos após o cadastro
        limparCampos();
    }

        private void capturarFotoAnimal() {
        JOptionPane.showMessageDialog(null, "Funcionalidade para capturar foto do animal ainda não implementada.");
    }

    private void voltarMenu() {
        this.setVisible(false);
        menu.setVisible(true);
    }
    
private void cadastrarDoenca() {
         String nome = txtNomeDoenca.getText().trim();
        String sintomas = txtSintomas.getText().trim();
        String tratamento = tratamentoTxtField.getText().trim();
        String informacoes = InfoDoenca.getText().trim();
        boolean picada = CasoforPicadacheckbox.isSelected();

        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe o nome da doença.");
            return;
         }

        // Cria uma nova instância de Doenca
        Doenca novaDoenca = new Doenca(nome, Arrays.asList(sintomas.split(",")), tratamento, informacoes, picada);
        DoencaManager.getInstance().adicionarDoenca(novaDoenca);

        JOptionPane.showMessageDialog(null, "Doença cadastrada com sucesso:\n" + novaDoenca.toString());

        // Limpa os campos após o cadastro
        limparCampos();
}


 
 
 private void limparCampos() {
        txtNomeDoenca.setText("");
        txtSintomas.setText("");
        tratamentoTxtField.setText("");
        InfoDoenca.setText("");
        CasoforPicadacheckbox.setSelected(false);
    }
 

 
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CadastroBtn = new javax.swing.JButton();
        txtNomeDoenca = new javax.swing.JTextField();
        txtSintomas = new javax.swing.JTextField();
        CasoforPicadacheckbox = new javax.swing.JCheckBox();
        FotoBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tratamentoTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoDoenca = new javax.swing.JTextArea();

        jLabel1.setText("Doença");

        jLabel2.setText("Sintomas");

        CadastroBtn.setText("Finalizar cadastro");
        CadastroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroBtnActionPerformed(evt);
            }
        });

        txtNomeDoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeDoencaActionPerformed(evt);
            }
        });

        txtSintomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSintomasActionPerformed(evt);
            }
        });

        CasoforPicadacheckbox.setText("Caso for picada");
        CasoforPicadacheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasoforPicadacheckboxActionPerformed(evt);
            }
        });

        FotoBtn.setText("Foto do animal se tiver");
        FotoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FotoBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Tratamento");

        tratamentoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratamentoTxtFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Um pouco sobre a doença");

        InfoDoenca.setColumns(20);
        InfoDoenca.setRows(5);
        jScrollPane1.setViewportView(InfoDoenca);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addComponent(txtNomeDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSintomas, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                    .addComponent(tratamentoTxtField))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CasoforPicadacheckbox)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CadastroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FotoBtn)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CasoforPicadacheckbox)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tratamentoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FotoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastroBtnActionPerformed

    private void CasoforPicadacheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasoforPicadacheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasoforPicadacheckboxActionPerformed

    private void txtNomeDoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeDoencaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeDoencaActionPerformed

    private void txtSintomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSintomasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSintomasActionPerformed

    private void FotoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FotoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FotoBtnActionPerformed

    private void tratamentoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tratamentoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tratamentoTxtFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarDeS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarDeS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarDeS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarDeS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarDeS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroBtn;
    private javax.swing.JCheckBox CasoforPicadacheckbox;
    private javax.swing.JButton FotoBtn;
    private javax.swing.JTextArea InfoDoenca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tratamentoTxtField;
    private javax.swing.JTextField txtNomeDoenca;
    private javax.swing.JTextField txtSintomas;
    // End of variables declaration//GEN-END:variables
}
